---
magento2_language: en_US
magento2_currency: USD
magento2_admin_user: admin
magento2_admin_password: admin2015
magento2_admin_email: null@magento.com
magento2_admin_firstname: John
magento2_admin_lastname: Doe
magento2_crypt_key: a7e7ab5cd150d7d7044eeada37af527b
magento2_base_url: http://192.168.33.10
magento_account_public_key: aadb19dd80a2466863bbea4647aa2184
magento_account_private_key: 5dc76165c464e06cdac15c4101e0f8da
